version: '2.3'
services:
  web:
    build:
      context: ~/Documents/GitHub/automation/automation-rules-engine
      dockerfile: Dockerfile
      target: base
    ports:
      - "9090:9090"
    command: npm run dev-server
    environment:
        ENV: staging
        PORT: 9090
        DB_MONGO_CLOUD_URL: docker.for.mac.host.internal:27017/automation?readPreference=primary&appname=RulesEngineMS